### PR TITLE
Added standard python gitignore

### PR DESCRIPTION
**Pull request by zacker150**
Gitignore file sourced from Gitignore file sourced from https://github.com/github/gitignore/blob/master/Python.gitignore

### CODE REVIEW

**Comment by crccheck** [comment]
I prefer minimal `.gitignore`s where every line is meaningful. Is this project really going to need a `.scrapy` file ignored?

**Comment by zacker150** [comment]
My philosophy is to avoid re-inventing the wheel and start with the standard gitignore files. We can always add or remove things as they become necessary.

**Comment by MalloyDelacroix** [comment]
I agree that we can add and remove from the standard list as needed.

However, I see this gitignore file excludes `.spec` files and we have two `.spec` files in the main directory that should be included.

**Comment by zacker150** [comment]
Odd. I thought I had already removed that from the gitignore. That has been fixed.

**Pull request merged**
